/**
 * Fills a running example app with real errors.
 *
 * Every issue here comes from code that actually ran and actually threw — the
 * example's failing routes, and a browser driven into its client error cases.
 * Nothing is fabricated.
 *
 * An earlier version posted invented stacks to bulk the data out, and that was
 * a mistake worth stating plainly: those issues named files that were never
 * built, so opening one showed no code. A demo whose issues cannot show the
 * failing line is worse than a smaller demo that can — the snippet is the
 * whole point of the tool.
 *
 * Volume comes from repetition instead: the same faults, from several
 * browsers, spread over time, which is also what real traffic looks like.
 *
 * "Spread over time" is done afterwards, in the database — see `spread()`.
 * Traffic is generated by real HTTP requests and a real browser, so every
 * event is stamped with the moment it happened, and the whole run takes about
 * a minute. That put all of it in one bucket at the right edge of a 24-hour
 * chart, which is exactly the screenshot the README leads with.
 *
 *   node scripts/seed.mjs [--url http://localhost:3000] [--scale 1] [--no-browser]
 *                         [--db path/to/monitor.db] [--no-spread]
 */

import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const args = new Map()

for (let i = 2; i < process.argv.length; i++) {
  const flag = process.argv[i]

  if (!flag?.startsWith('--')) {
    continue
  }

  const next = process.argv[i + 1]
  // `--scale 2` takes a value; `--no-browser` is a bare switch. Deciding by
  // what follows keeps both forms working without a schema.
  const takesValue = next !== undefined && !next.startsWith('--')

  args.set(flag.replace(/^--/, ''), takesValue ? next : true)

  if (takesValue) {
    i++
  }
}

const BASE = (args.get('url') ?? 'http://localhost:3000').replace(/\/$/, '')
const SCALE = Number(args.get('scale') ?? 1)

/**
 * Real strings, because the parser is real.
 *
 * These reach the server as a `User-Agent` header and are parsed there, so the
 * browser and OS facets end up populated exactly as they would in production.
 */
const AGENTS = {
  chrome: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
    + '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  firefox: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0',
  safari: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 '
    + '(KHTML, like Gecko) Version/17.1 Safari/605.1.15',
  ios: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/605.1.15 '
    + '(KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1',
  android: 'Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 '
    + '(KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36',
}

/** The example's server-side failures, each a distinct capture path. */
const SERVER_CASES = [
  { path: '/api/throw', weight: 4 },
  { path: '/api/create-error', weight: 3 },
  { path: '/api/async-throw', weight: 3 },
  { path: '/api/scrub-me?token=leaked-secret', weight: 2 },
  { path: '/middleware-error', weight: 5 },
  { path: '/ssr-error', weight: 3 },
]

/**
 * Successful traffic, so the error rate has a denominator.
 *
 * `/api/reconcile` is in here rather than among the failures on purpose: it
 * answers 200 and reports through `exception()`, which is the whole point of
 * that route. It also gives the dashboard manual reports to filter by, and the
 * notification routing two named groups to route on.
 */
const HEALTHY = ['/', '/client-error', '/fetch-error', '/api/reconcile']

let requests = 0

function pick(values, index) {
  return values[index % values.length]
}

async function hit(path, agent) {
  await fetch(`${BASE}${path}`, { headers: { 'user-agent': agent } }).catch(() => {})
  requests++
}

/**
 * Drives a real browser through the example's client error cases.
 *
 * The only way to get a client error whose stack points at code that exists.
 * Optional: `playwright-core` is a dev dependency of the repo, not of the
 * module, and the seeder is still worth running without it — there just will
 * not be any client-side issues.
 */
async function clientErrors() {
  let chromium

  try {
    ({ chromium } = await import('playwright-core'))
  }
  catch {
    console.log('· skipping client errors (playwright-core not installed)')
    return
  }

  let browser

  try {
    browser = await chromium.launch({ channel: 'chromium' })
  }
  catch {
    console.log('· skipping client errors (no Chromium available)')
    return
  }

  const rounds = Math.max(1, Math.round(3 * SCALE))

  try {
    for (let round = 0; round < rounds; round++) {
      // A fresh context per round means a fresh sessionStorage, and so a
      // distinct session — which is what makes the session counts meaningful.
      const context = await browser.newContext({ userAgent: pick(Object.values(AGENTS), round) })
      const page = await context.newPage()

      // A component error raised after hydration, through `vue:error`.
      await page.goto(`${BASE}/client-error`, { waitUntil: 'networkidle' }).catch(() => {})
      await page.waitForTimeout(900)
      await page.click('button').catch(() => {})
      await page.waitForTimeout(900)

      // Errors outside Vue: a throwing handler, a rejected promise, a timer.
      await page.goto(BASE, { waitUntil: 'networkidle' }).catch(() => {})
      await page.waitForTimeout(900)

      for (const label of ['Thrown from a click', 'Unhandled rejection', 'Thrown from a timer']) {
        await page.getByRole('button', { name: new RegExp(label, 'i') }).click().catch(() => {})
        await page.waitForTimeout(300)
      }

      // Route middleware, and a `useFetch` against a failing route.
      await page.goto(`${BASE}/route-middleware-error`, { waitUntil: 'networkidle' }).catch(() => {})
      await page.waitForTimeout(700)
      await page.goto(`${BASE}/fetch-error`, { waitUntil: 'networkidle' }).catch(() => {})
      await page.waitForTimeout(900)

      // The queue batches and flushes on hide; without this the last events
      // leave with the browser.
      await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange'))).catch(() => {})
      await page.waitForTimeout(700)
      await context.close()
    }

    console.log(`· client errors captured (${rounds} ${rounds === 1 ? 'session' : 'sessions'})`)
  }
  finally {
    await browser.close()
  }
}

/**
 * Backdates what was just collected, so the window has a shape.
 *
 * Done in the database rather than through the ingest API because the server
 * side cannot be backdated at all: those events come from real requests, and
 * their timestamp is when the request happened. Rewriting afterwards is the
 * only way to get one story across both sides.
 *
 * Three tables move together, or the dashboard contradicts itself: `events`
 * carries the occurrences, `request_stats` the denominator behind every rate,
 * and `issues` the first/last seen shown in every list. Derived from the same
 * offsets, so an issue's "last seen" is still the newest event it has.
 */
async function spread(dbPath) {
  const { DatabaseSync } = await import('node:sqlite')

  let db

  try {
    db = new DatabaseSync(dbPath)
  }
  catch {
    console.log(`· skipping time spread (no database at ${dbPath})`)
    return
  }

  const now = Date.now()

  /**
   * Six days, not twenty hours.
   *
   * The seed used to fill just under the window the dashboard opens on, which
   * made every other window useless: `7d` showed the same crowd of points
   * bunched against its right edge, and `1h` was empty as often as not. Six
   * days fills `7d` with something shaped, and the curve below still leaves
   * plenty inside the last day and the last hour.
   */
  const WINDOW = 6 * 24 * 60 * 60 * 1_000

  try {
    const events = db.prepare('SELECT id, ts FROM events ORDER BY id').all()

    if (!events.length) {
      return
    }

    /**
     * Oldest event first, newest last, spread across the whole window.
     *
     * The offset falls geometrically rather than by a power of the position,
     * and the reason is that the dashboard has four windows, not one. A power
     * curve is tuned to whichever span it was drawn against: `(1 - p) ** 1.35`
     * across six days leaves the last hour empty, and the exponent that fills
     * the last hour piles everything there and empties the week.
     *
     * Halving the offset repeatedly is the same shape at every zoom level —
     * each window shows roughly a fixed share of the events, so `7d`, `24h`
     * and `1h` are all populated by one pass. `DECADES` sets how many halvings
     * fit in the window. At 8, roughly a tenth of the events land in the last
     * hour, two thirds within the last day, and the remaining third spreads
     * back across the week — every window has something in it.
     *
     * `id` order is insertion order, which is collection order, so this keeps
     * events in the sequence they actually happened.
     */
    const DECADES = 8

    const offsetAt = (index) => {
      const position = index / Math.max(1, events.length - 1)

      return Math.round(WINDOW * 2 ** (-DECADES * position))
    }

    const update = db.prepare('UPDATE events SET ts = ? WHERE id = ?')

    db.exec('BEGIN')

    events.forEach((event, index) => {
      update.run(now - offsetAt(index), event.id)
    })

    // Issue bounds are recomputed from the events they own rather than shifted
    // by a matching offset — the events moved independently, so anything else
    // would leave an issue claiming a `last_seen` no event of its has.
    db.exec(`
      UPDATE issues SET
        first_seen = (SELECT MIN(ts) FROM events WHERE events.fingerprint = issues.fingerprint),
        last_seen  = (SELECT MAX(ts) FROM events WHERE events.fingerprint = issues.fingerprint)
      WHERE EXISTS (SELECT 1 FROM events WHERE events.fingerprint = issues.fingerprint)
    `)

    /**
     * Counters are split across the window rather than shifted onto it.
     *
     * Shifting by source position was the obvious move and it does not work:
     * the whole run takes about a minute, so every counter lands in one of
     * three or four minute-buckets, and moving four points around a day still
     * leaves four points. A traffic chart drawn from that is four bars.
     *
     * So each counter row is divided into slices spread over the window, on
     * the same curve the events follow — requests and the failures among them
     * stay in step, and the error rate per hour keeps meaning something.
     *
     * Keyed by bucket, so they cannot be updated in place: two slices can land
     * on one bucket and collide with the primary key. Delete and re-insert
     * through an upsert that merges collisions.
     */
    // Summed across the source buckets first: the same route/method/class can
    // appear in several minutes, and each must be spread once, not once per
    // minute it happened to land in.
    const counters = db.prepare(`
      SELECT route, method, class, SUM(count) AS count
      FROM request_stats
      GROUP BY route, method, class
    `).all()

    if (counters.length) {
      const BUCKET_MS = 60_000
      /**
       * Two slices per column the widest chart draws.
       *
       * The chart always splits its window into 48 columns, whichever window
       * that is. Slices placed on a geometric curve crowd towards the present,
       * so one-per-column across a week leaves the older columns bare; twice
       * that many keeps them filled and merely doubles up on the recent ones,
       * which the upsert below sums back together.
       */
      const SLICES = 96

      db.exec('DELETE FROM request_stats')

      const insert = db.prepare(`
        INSERT INTO request_stats (bucket, route, method, class, count) VALUES (?, ?, ?, ?, ?)
        ON CONFLICT(bucket, route, method, class) DO UPDATE SET count = count + excluded.count
      `)

      /**
       * Where slice `i` lands, on the curve the events already follow.
       *
       * Requests and the failures among them have to sit on the same curve, or
       * the error rate per hour stops meaning anything: events bunched near
       * `now` against requests spread flat reads as a spike that never
       * happened.
       */
      const sliceOffset = i =>
        Math.round(WINDOW * 2 ** (-DECADES * (i / Math.max(1, SLICES - 1))))

      /**
       * Every slice carries the same share — the tilt is already in where the
       * slices sit.
       *
       * The events are spread one per position along the same curve, so an
       * equal share per slice reproduces their distribution exactly: both end
       * up with about two thirds inside the last day. Adding a second weight
       * on top of the geometric spacing squares the curve, and the error rate
       * goes with it — requests piling into the last hours while the errors
       * sit further back, or the reverse.
       */
      for (const row of counters) {
        let placed = 0

        for (let i = 0; i < SLICES; i++) {
          const remaining = row.count - placed

          /**
           * Distributed by running total rather than rounded per slice.
           *
           * Rounding each slice independently sends every share below half a
           * request to zero, so a route with twelve requests lands in three
           * buckets and the chart is mostly gaps. Comparing cumulative targets
           * spends the whole count across the window: small counters simply
           * skip slices instead of collapsing into the last one.
           */
          const target = Math.round((row.count * (i + 1)) / SLICES)

          const share = i === SLICES - 1 ? remaining : Math.max(0, target - placed)

          if (share <= 0) {
            continue
          }

          placed += share

          /**
           * Placed on the event curve, snapped only to the minute the counters
           * are keyed by.
           *
           * Snapping to the chart's own column width is what the earlier
           * version did, and it cannot work across four windows: the width of
           * a `7d` column is three and a half hours, which would round every
           * slice inside the last hour onto the same bucket and leave `1h`
           * showing one bar. The minute grid is fine for all of them — the
           * chart regroups buckets into columns itself, and gaps only appear
           * when slices are *sparser* than the columns, which the count above
           * prevents.
           */
          const at = now - sliceOffset(i)

          insert.run(
            Math.floor(at / BUCKET_MS) * BUCKET_MS,
            row.route,
            row.method,
            row.class,
            share,
          )
        }
      }
    }

    db.exec('COMMIT')

    console.log(`· spread ${events.length} events over the last ${WINDOW / 86_400_000}d`)
  }
  catch (caught) {
    db.exec('ROLLBACK')
    console.log(`· could not spread over time: ${caught.message}`)
  }
  finally {
    db.close()
  }
}

async function main() {
  const reachable = await fetch(BASE, { method: 'HEAD' }).catch(() => null)

  if (!reachable) {
    console.error(`No server at ${BASE}. Start one first, e.g. \`pnpm demo\`.`)
    process.exit(1)
  }

  console.log(`Seeding ${BASE} (scale ${SCALE})…`)

  // Server errors, weighted so the list has a shape rather than one of each.
  const agents = Object.values(AGENTS)
  let index = 0

  for (const testCase of SERVER_CASES) {
    for (let i = 0; i < Math.round(testCase.weight * SCALE); i++) {
      await hit(testCase.path, pick(agents, index++))
    }
  }

  // Successful requests, so error rates are a fraction of something.
  for (let i = 0; i < Math.round(40 * SCALE); i++) {
    await hit(pick(HEALTHY, i), pick(agents, index++))
  }

  console.log(`· ${requests} requests made`)

  if (args.get('no-browser') === undefined) {
    await clientErrors()
  }

  if (args.get('no-spread') === undefined) {
    // Events and counters are buffered in memory and flushed on a timer, so
    // rewriting timestamps immediately would miss the tail of the run — and
    // the flush would then write those rows back at their original time.
    await new Promise(resolve => setTimeout(resolve, 2_500))

    const dbPath = args.get('db')
      ?? join(dirname(fileURLToPath(import.meta.url)), '..', 'example', '.monitor', 'monitor.db')

    await spread(dbPath)
  }

  console.log(`\nDone. Open ${BASE}/_monitor to see them.`)
}

await main()
